Source/LapTrinhHienDai-128-178-474/LapTrinhHienDai-128-178-474/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LapTrinhHienDai_128_178_474.Models;

namespace LapTrinhHienDai_128_178_474.Controllers
{
    public class HomeController : Controller
    {
        PortalEntities dbContext = new PortalEntities();

        public ActionResult Index()
        {
            ViewBag.ThanhPhos = new SelectList(from p in dbContext.ThanhPho orderby p.TenThanhPho select p  , "MaThanhPho", "TenThanhPho");
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Source/LapTrinhHienDai-128-178-474/LapTrinhHienDai-128-178-474/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LapTrinhHienDai_128_178_474.Models;
using LapTrinhHienDai_128_178_474.Helpers;
using System.Data.Entity.Validation;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using WebMatrix.WebData;
using System.Net.Http.Headers;
using System.Net.Http.Formatting;
using HtmlAgilityPack;

namespace LapTrinhHienDai_128_178_474.Controllers
{
    public class HotelController : Controller
    {
        //
        // GET: /Hotel/

        PortalEntities dbContext = new PortalEntities();

        //số kết quả mặc định trong một trang
        public const int PageSize = 8;


        //duyệt khách sạn theo thành phố
        public ActionResult HotelList(string City, string sortBy, int page)
        {
            var hotels = new PagedData<KhachSan>();
            switch (sortBy)
            {
                case "NAME":
                    hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.TenKhachSan).Skip(PageSize * (page - 1)).Take(PageSize).ToList();
                    break;
                case "PRICE":
                    hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.GiaTien).Skip(PageSize * (page - 1)).Take(PageSize).ToList();
                    break;
                case "CATEGORY":
                    hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.HangKhachSan).Skip(PageSize * (page - 1)).Take(PageSize).ToList();
                    break;
                case "RATING":
                    hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.DanhGia).Skip(PageSize * (page - 1)).Take(PageSize).ToList();
                    break;
                default:
                    hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.TenKhachSan).Skip(PageSize * (page - 1)).Take(PageSize).ToList();
                    break;
            }
            hotels.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)dbContext.KhachSan.Where(ks => ks.ThanhPho == City).Count() / PageSize));
            hotels.CurrentPage = page;
            return PartialView(hotels);
        }


        //tìm kiếm khách sạn
        [AllowAnonymous]
        public ActionResult Search(string City,string HotelName,string sortBy)
        {
            var hotels = new PagedData<KhachSan>();
            if (String.IsNullOrEmpty(HotelName))
            {
                switch (sortBy)
                {
                    case "NAME":
                        hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.TenKhachSan).Take(PageSize).ToList();
                        break;
                    case "PRICE":
                        hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.GiaTien).Take(PageSize).ToList();
                        break;
                    case "CATEGORY":
                        hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderByDescending(ks => ks.HangKhachSan).Take(PageSize).ToList();
                        break;
                    case "RATING":
                        hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderByDescending(ks => ks.DanhGia).Take(PageSize).ToList();
                        break;
                    default:
                        hotels.Data = dbContext.KhachSan.Where(ks => ks.ThanhPho == City).OrderBy(ks => ks.TenKhachSan).Take(PageSize).ToList();
                        break;
                }
            }
            else
            {
                var khachSanCanTim = (from ks in dbContext.KhachSan
                                      where ks.TenKhachSan.ToLower().Contains(HotelName.ToLower())
                                      select ks).ToList();
                if (khachSanCanTim == null){
                    //return ViewResult("NotFound");
                }
                else{
                    hotels.Data = khachSanCanTim;
                }
            }
            hotels.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)dbContext.KhachSan.Where(ks => ks.ThanhPho == City).Count() / PageSize));
            hotels.CurrentPage = 1;
            ViewBag.CityCode = City;
            ViewBag.CityName = hotels.Data.FirstOrDefault().ThanhPho1.TenThanhPho;
            return View(hotels);
        }
  
        //trang chi tiêt khách sạn
        public ActionResult Detail(int Id)
        {
            KhachSan hotel = dbContext.KhachSan.Find(Id);
            ViewBag.CityName = hotel.ThanhPho1.TenThanhPho;

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:55113/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync("api/Sheraton/LayDanhSachLoaiPhong").Result;
            if (response.IsSuccessStatusCode )
            {
                ViewBag.LoaiPhongs = response.Content.ReadAsAsync<List<LoaiPhong>>().Result;
            }

            //trích rút nội dung website
            //string webUrl = "http://www.buaxua.vn/Thong-tin-can-biet/Cac-dia-diem-tham-quan-du-lich-tai-Ha-Noi.html";
            //HtmlDocument htmlDoc = new HtmlDocument();
            //HtmlWeb webGet = new HtmlWeb();
            //htmlDoc = webGet.Load(webUrl);

            //var _content = htmlDoc.DocumentNode.SelectSingleNode("//body");
            //ViewBag.NoiDungRutTrich = _content.InnerHtml;
            ViewBag.NoiDungRutTrich = "HelloWorld";
            return View(hotel); 
        }

        //xem danh sách bình luận
        [ChildActionOnly]
        public ActionResult CommentList(List<BinhLuan> Comments)
        {
            return PartialView(Comments);
        }

        [HttpPost]
        [Authorize]
        public PartialViewResult AddComment(String HotelId, String CommentRating, String CommentContent)
        {
            //var hotel = dbContext.KhachSan.Find(int.Parse(HotelId));
            BinhLuan binhLuan = new BinhLuan();
            binhLuan.NoiDung = CommentContent;
            binhLuan.DiemDanhGia = int.Parse(CommentRating);
            binhLuan.NguoiBinhLuan = User.Identity.Name;
            binhLuan.ThoiGian = DateTime.Now.ToLocalTime().ToString();
            binhLuan.KhachSan = int.Parse(HotelId);
            //binhLuan.KhachSan1 = hotel;
            switch (CommentRating)
            {
                case "1":
                    binhLuan.TieuDe = "Rất không hài lòng";
                    break;
                case "2":
                    binhLuan.TieuDe = "Không hài lòng";
                    break;
                case "3":
                    binhLuan.TieuDe = "Tạm được";
                    break;
                case "4":
                    binhLuan.TieuDe = "Hài lòng";
                    break;
                case "5":
                    binhLuan.TieuDe = "Rất hài lòng";
                    break;
                default:
                    binhLuan.TieuDe = "Không rõ";
                    break;
            }
            dbContext.BinhLuan.Add(binhLuan);
            try
            {
                dbContext.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                //foreach (var err in e.EntityValidationErrors)
                //{
                //    foreach (var err1 in err.ValidationErrors)
                //    {
                //        Console.WriteLine(err1.ErrorMessage);
                //    }
                //}
            }
            
            return PartialView("SingleComment", binhLuan);
        }


        [Authorize]
        public ActionResult LichSuDatPhong()
        {
            var lichSuDatPhong = (from dp in dbContext.DonDatPhong where dp.MaKhachHang == User.Identity.Name.Trim() select dp).ToList();
            ViewBag.LichSuDatPhong = lichSuDatPhong;
            return View();
        }
    }
}

Source/LapTrinhHienDai-128-178-474/LapTrinhHienDai-128-178-474/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

Source/LapTrinhHienDai-128-178-474/LapTrinhHienDai-128-178-474/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

Source/LapTrinhHienDai-128-178-474/LapTrinhHienDai-128-178-474/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#date1').val(new Date.today().toString("dd/MM/yyyy"));
        $('#date2').val(new Date.today().addDays(1).toString("dd/MM/yyyy"));

        $('#date1').Zebra_DatePicker({
            direction: true,
            pair: $('#date2'),
            format: 'd/m/Y',
            show_clear_date: false
        });
        $('#date2').Zebra_DatePicker({
            direction: 1,
            format: 'd/m/Y',
            show_clear_date: false
        });
    });
</script>

<article id="home">
    <figure class="image-c">
        <a href="./">
            <img src="~/Content/aTourist/temp/featured-a.jpg" alt="Featured" width="1260" height="700"></a> <figcaption>Need a luxury room for your holiday <span>Paris Hilton hotel</span> <span>$450  /  night</span></figcaption>
    </figure>
    <form action="@Url.Action("Search", "Hotel")" method="post" class="form-c" style="width:250px">
        <fieldset>
            <legend>Tìm kiếm nhanh</legend>
            <h3><span>01.</span> Lựa chọn địa điểm ?</h3>
            <select style="width: 100%" class="customSelect" id="" name="City">
                @foreach (var thanhPho in ViewBag.ThanhPhos)
                {
                    <option value="@thanhPho.Value.Trim()">@thanhPho.Text</option>
                }
            </select>
            <h3><span>02.</span> Nhập tên khách sạn ?</h3>
            <p>
                <input type="text" id="" name="HotelName" style="width: 90%; height: 24px; font-size: 12px; padding-left: 20px; border: 1px solid #808080" placeholder="VD: Novotel, Sheraton ..." />
            </p>
            <h3><span>03.</span> Lựa chọn thời gian đặt phòng?</h3>
            <p style="font-size: 12px">
                Từ
                <input id="date1" style="width: 40%; height: 24px" />
                đến
                <input id="date2" style="width: 40%; height: 24px" />
            </p>
            <h3><span>04.</span> Lựa chọn số lượng?</h3>
            <p class="select-a">
                <span>
                    <label for="fce">Số phòng</label>
                    <select id="fce" name="fce">
                        <option>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                    </select>
                </span>
                <span>
                    <label for="fcf">Số người lớn</label>
                    <select id="fcf" name="fcf">
                        <option>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                    </select>
                </span>
                <span>
                    <label for="fcg">Số trẻ em</label>
                    <select id="fcg" name="fcg">
                        <option>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                    </select>
                </span>
            </p>
            <h3><span>05.</span> Sắp xếp theo?</h3>
            <p>
                <select style="width: 100%" class="customSelect" id="" name="sortBy">
                    <option value="CATEGORY">Hạng khách sạn</option>
                    <option value="PRICE">Giá khách sạn</option>
                    <option value="RATING">Đánh giá người dùng</option>
                    <option value="NAME">Tên khách sạn</option>
                </select>
            </p>
            <p class="submit">
                <button type="submit">Tìm kiếm</button>
            </p>
        </fieldset>
    </form>
</article>